#!/bin/sh
mvn clean package && docker build -t maryamshaikh/MSASecondClientApp .
docker rm -f MSASecondClientApp 2>/dev/null || true && docker run -it --name MSASecondClientApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MSASecondClientApp maryamshaikh/MSASecondClientApp
